'use strict';
const fs = require('fs'), assert = require('assert'), { JSDOM } = require('jsdom');
const dom = new JSDOM('<html><head></head><body></body></html>');
global.window = dom.window; global.document = window.document; global.MutationObserver = window.MutationObserver;
const calls = []; let checked = { success: true, candidate_id: 'a'.repeat(32), tag_name: 'v1' }, rejectCheck = false;
const pending = {};
const defer = method => { let resolve, reject; const promise = new Promise((yes,no) => { resolve=yes; reject=no; }); pending[method]=promise; return {resolve,reject}; };
const rpc = { declare: d => (...args) => { calls.push([d.method, args]); if (pending[d.method]) { const promise=pending[d.method]; delete pending[d.method]; return promise; } if (d.method === 'checkUpdate') return rejectCheck ? Promise.reject(Error('offline')) : Promise.resolve(checked); return Promise.resolve({ success: true }); } };
const E = (tag, attrs = {}, children = []) => { const n = document.createElement(tag); Object.entries(attrs).forEach(([k,v]) => { if (k === 'click') n.addEventListener('click',v); else if (k === 'checked') n.checked = v; else n.setAttribute(k,v); }); (Array.isArray(children) ? children : [children]).forEach(c => n.append(c && c.nodeType ? c : String(c))); return n; };
let modal;
const ui = { createHandlerFn: (ctx, name, ...args) => ev => ctx[name](...args,ev), showModal: (title, nodes) => { modal=E('div',{},nodes); document.body.append(modal); }, hideModal: () => modal && modal.remove() };
const polling = new Set(), poll={add: fn=>polling.add(fn),remove: fn=>polling.delete(fn)};
const source=fs.readFileSync(__dirname+'/../htdocs/luci-static/resources/view/firmwareupgrade/index.js','utf8');
const app=Function('rpc','view','ui','poll','E','_','L',source)(rpc,{extend:x=>x},ui,poll,E,x=>x,{bind:(fn,ctx)=>fn.bind(ctx)});
(async()=>{
 document.body.append(app.render({repository:'owner/repo'}));
 const root=document.querySelector('.fwup-dashboard'), notice=root.querySelector('[style="display:none"]'), latest=document.querySelector('#fwup-latest'), detail=document.querySelector('#fwup-detail').parentNode;
 assert(document.getElementById('fwup-release-pattern'), 'release rule field');
 assert(document.getElementById('fwup-asset-pattern'), 'asset rule field');
 const button=[...root.querySelectorAll('button')].find(x=>x.textContent==='Check update');
 await app.check(notice,latest,detail,{currentTarget:button});
 const upgrade=[...root.querySelectorAll('button')].find(x=>x.textContent==='Upgrade firmware');
 assert(detail.classList.contains('fwup-release'), 'release shares the operation alignment instead of a nested panel');
 const css=root.querySelector('style').textContent;
 assert(css.includes('flex-wrap:wrap;margin:16px 0'));
 assert(css.includes('height:32px;min-height:32px;margin:0'));
 assert(css.includes('.fwup-modal .fwup-progress{'), 'body-mounted modal progress must not depend on dashboard ancestry');
 assert(css.includes('max-width:min(560px,calc(100vw - 32px))'), 'modal fits tablet and phone');
 upgrade.click();
 // Changing a later discovery must not change the image already confirmed.
 checked={success:true,candidate_id:'b'.repeat(32),tag_name:'v2'};
 await app.check(notice,latest,detail,{currentTarget:button});
 [...modal.querySelectorAll('button')].find(x=>x.textContent==='Start upgrade').click();
 await new Promise(resolve=>setImmediate(resolve));
 assert.deepStrictEqual(calls.find(x=>x[0]==='startUpgrade')[1],['0','a'.repeat(32)]);
 rejectCheck=true; await app.check(notice,latest,detail,{currentTarget:button});
 assert.strictEqual(detail.style.display,'none'); assert.strictEqual(document.querySelector('#fwup-detail').textContent,'');
 assert.strictEqual(latest.textContent,'Not checked');
 document.getElementById('fwup-repo').value='another/repo';
 document.getElementById('fwup-repo').dispatchEvent(new window.Event('input'));
 assert.strictEqual(document.getElementById('fwup-release-pattern').value,'');
 assert.strictEqual(document.getElementById('fwup-asset-pattern').value,'');
 const before=calls.length; await app.check(notice,latest,detail,{currentTarget:button});
 assert.strictEqual(calls.length,before,'unsaved rules must not check old repository');
 const saveButton=[...root.querySelectorAll('button')].find(x=>x.textContent==='Save settings');
 await app.save(notice,{currentTarget:saveButton});
 rejectCheck=false;
 const delayed=defer('checkUpdate');
 const checking=app.check(notice,latest,detail,{currentTarget:button});
 document.getElementById('fwup-repo').value='edited/during-check';
 document.getElementById('fwup-repo').dispatchEvent(new window.Event('input'));
 delayed.resolve(checked); await checking;
 assert.strictEqual(detail.style.display,'none','old check must not restore upgrade controls after editing');
 assert.strictEqual(latest.textContent,'Not checked');
 assert.strictEqual(app.settingsDirty,true);
 const savingReply=defer('saveSettings');
 const saving=app.save(notice,{currentTarget:saveButton});
 document.getElementById('fwup-repo').value='edited/during-save';
 document.getElementById('fwup-repo').dispatchEvent(new window.Event('input'));
 savingReply.resolve({success:true}); await saving;
 assert.strictEqual(app.settingsDirty,true,'old save must not mark newer edits saved');
 const afterSave=calls.length; await app.check(notice,latest,detail,{currentTarget:button});
 assert.strictEqual(calls.length,afterSave,'new edits still block checking after old save success');
 await app.save(notice,{currentTarget:saveButton});
 assert.strictEqual(app.settingsDirty,false,'saving current revision clears dirty state');
 await app.check(notice,latest,detail,{currentTarget:button});
 assert.strictEqual(detail.style.display,'');
 // One in-flight settings operation: no duplicate or cross-method races.
 for (const method of ['checkUpdate','saveSettings']) {
  const reply=defer(method);
  const operation=method==='checkUpdate' ? app.check(notice,latest,detail,{currentTarget:button}) : app.save(notice,{currentTarget:saveButton});
  const count=calls.length;
  await app.check(notice,latest,detail,{currentTarget:button});
  await app.save(notice,{currentTarget:saveButton});
  assert.strictEqual(calls.length,count,'check/save requests must not overlap');
  reply.resolve(method==='checkUpdate' ? checked : {success:true}); await operation;
 }
 for (const id of ['fwup-token','fwup-keep']) {
  const reply=defer('saveSettings'); const operation=app.save(notice,{currentTarget:saveButton});
  document.getElementById(id).dispatchEvent(new window.Event('input'));
  reply.resolve({success:true}); await operation;
  assert.strictEqual(app.settingsDirty,true,id+' edits during save remain dirty');
  await app.save(notice,{currentTarget:saveButton});
 }
 console.log('PASS: actual view confirmation, failures, edit revisions and serialized check/save regressions');
})().catch(e=>{console.error(e);process.exitCode=1;});
