const {boot}=require('./luci-dom.cjs');const assert=require('assert/strict');
const results=[];
async function edit(x){await x.map.children[0].renderMoreOptionsModal('test');const node=x.w.document.querySelector('.modal .cbi-map');return node?x.mods.dom.findClassInstance(node):null;}
function set(x,key,value){const e=x.w.document.getElementById('widget.cbid.wireless.test.'+key);assert(e,'missing widget '+key);e.value=value;e.dispatchEvent(new x.w.Event('change',{bubbles:true}));return e;}
async function test(name,opts,fn){let x;try{x=await boot(opts);const detail=await fn(x);results.push({name,pass:true,hash:x.hash,detail});}catch(e){results.push({name,pass:false,hash:x?.hash,error:e.stack});}finally{x?.j.window.close();}}
(async()=>{
 await test('main table structure',{},async x=>{const cols=[...x.node.querySelectorAll('thead th,.table-titles .th')].map(e=>e.textContent);const visible=x.map.children[0].children.filter(o=>!o.modalonly).map(o=>o.option);assert(visible.includes('_overview'));assert(visible.every(v=>['_overview','_runtime'].includes(v)));assert(!x.node.textContent.includes(',, '));assert(!x.node.textContent.includes('[object'));assert.equal(x.node.querySelectorAll('[data-mlo-overview-section] .cbi-value').length,4);return {cols,visible};});
 for(const mode of ['mesh','adhoc'])await test('unsupported mode preserved '+mode,{iface:{mode}},async x=>{const before=JSON.stringify(x.db.wireless.test);const m=await edit(x);if(!m){assert.equal(JSON.stringify(x.db.wireless.test),before);return 'edit blocked';}await x.map.children[0].handleModalSave(m,{});assert.equal(x.db.wireless.test.mode,mode);});
 for(const encryption of ['psk2+ccmp','wpa2'])await test('unsupported encryption preserved '+encryption,{iface:{encryption}},async x=>{const m=await edit(x);if(m)await x.map.children[0].handleModalSave(m,{});assert.equal(x.db.wireless.test.encryption,encryption);assert.equal(x.db.wireless.test.key,'audit-password');});
 await test('edited SSID saves through real modal',{},async x=>{const m=await edit(x);set(x,'ssid','Saved-Audit');await x.map.children[0].handleModalSave(m,{});assert.equal(x.db.wireless.test.ssid,'Saved-Audit');assert(x.writes.some(v=>v[3]==='ssid'&&v[4]==='Saved-Audit'));});
 await test('edit cancel leaves UCI unchanged',{},async x=>{const before=JSON.stringify(x.db);const m=await edit(x);set(x,'ssid','Canceled');await x.map.children[0].handleModalCancel(m,{});assert.equal(JSON.stringify(x.db),before);});
 for(const mode of ['ap','sta'])await test('quick add '+mode+' cancel',{},async x=>{const before=Object.keys(x.db.wireless);const btn=[...x.node.querySelectorAll('button')].find(e=>e.textContent.includes('Quick Add '+mode.toUpperCase()))||[...x.node.querySelectorAll('button')].find(e=>e.textContent.includes('Add MLO'));assert(btn);btn.click();await new Promise(r=>setTimeout(r,40));const modal=x.w.document.querySelector('.modal .cbi-map');assert(modal,'Quick Add did not open an editor');const m=x.mods.dom.findClassInstance(modal);const sid=Object.keys(x.db.wireless).find(s=>!before.includes(s));const selector=x.w.document.getElementById('widget.cbid.wireless.'+sid+'.mode');assert(selector);selector.value=mode;selector.dispatchEvent(new x.w.Event('change',{bubbles:true}));await x.map.children[0].handleModalCancel(m,{});await x.map.save();assert.deepEqual(Object.keys(x.db.wireless),before);});
 for(const mode of ['ap','sta'])await test('mode switch '+mode+' saves and returns',{iface:{mode}},async x=>{let m=await edit(x);const other=mode==='ap'?'sta':'ap';set(x,'mode',other);assert.equal(m.lookupOption('bssid','test')[0].isActive('test'),other==='sta');await x.map.children[0].handleModalSave(m,{});assert.equal(x.db.wireless.test.mode,other);m=await edit(x);set(x,'mode',mode);assert.equal(m.lookupOption('hidden','test')[0].isActive('test'),mode==='ap');await x.map.children[0].handleModalSave(m,{});assert.equal(x.db.wireless.test.mode,mode);});
 for(const encryption of ['sae','owe'])await test('PMF '+encryption+' fixed required',{iface:{ieee80211w:'0'}},async x=>{const m=await edit(x);set(x,'encryption',encryption);const option=m.lookupOption('_pmf_required','test')[0];assert.equal(option.isActive('test'),true);assert.equal(option.readonly,true);assert.equal(option.formvalue('test'),'2');assert.equal(m.lookupOption('ieee80211w','test')[0].isActive('test'),false);await x.map.children[0].handleModalSave(m,{});assert.equal(x.db.wireless.test.ieee80211w,'2');assert(!('_pmf_required' in x.db.wireless.test));});
 await test('unknown RPC stays unknown',{unknown:true},async x=>{assert.match(x.node.textContent,/unavailable|unknown|failed/i);return x.node.textContent;});
 await test('readonly prevents writes',{readonly:true},async x=>{const bad=[...x.node.querySelectorAll('button')].filter(e=>/Quick Add|Delete|Add MLO/.test(e.textContent)&&!e.disabled);assert.equal(bad.length,0,bad.map(e=>e.textContent).join(','));assert.equal(x.writes.length,0);});
 await test('modal actual DOM export',{},async x=>{await edit(x);return [...x.w.document.querySelectorAll('.modal input,.modal select')].length;});
 for(const r of results)console.log(r.pass?'PASS':'FAIL',r.name,r.error?.split('\n')[0]||'');console.log(JSON.stringify({passed:results.filter(r=>r.pass).length,total:results.length}));process.exitCode=results.some(r=>!r.pass)?1:0;
})().catch(e=>{console.error(e);process.exitCode=1});
