const fs=require('fs'),assert=require('assert/strict');const {JSDOM}=require('jsdom');const w=new JSDOM('<body/>').window;global.document=w.document;global.requestAnimationFrame=callback=>setTimeout(callback,0);global.MutationObserver=w.MutationObserver;
String.prototype.format=function(...a){let i=0;return this.replace(/%[sd]/g,()=>a[i++]);};
const E=(tag,attrs,children)=>{if(Array.isArray(attrs)||typeof attrs==='string'){children=attrs;attrs={}};let n=document.createElement(tag);for(let[k,v]of Object.entries(attrs||{}))if(typeof v==='function')n.addEventListener(k,v);else if(v!=null)n.setAttribute(k,v);for(let c of [children].flat(Infinity))if(c!=null)n.append(c);return n};
let grid,tick,count=0,fail=false,removed=0;let cfg={'.name':'mlo0',mode:'ap',mlo:'1',device:['r0','r1'],encryption:'sae'};
const uci={load:()=>Promise.resolve(),get:()=>cfg,sections:(c,t)=>t==='wifi-iface'?[cfg]:t==='wifi-device'?[{'.name':'r0'},{'.name':'r1'}]:[]};const form={GridSection:{prototype:{}},Map:function(){this.chain=()=>{};this.section=()=>grid={children:[],tab:()=>{},option:function(t,n){let o={option:n,value:()=>{},depends:()=>{}};this.children.push(o);return o},taboption:function(t,...a){return this.option(...a)}};this.render=()=>Promise.resolve(E('div',{},grid.children.filter(o=>!o.modalonly).map(o=>o.textvalue('mlo0'))))}};
const rpc={declare:()=>()=>{count++;return fail?Promise.reject(Error('denied')):Promise.resolve({r0:{up:true,interfaces:[{section:'mlo0',ifname:'custom0',mld:true,config:{device:['r0','r1']}}]}})}};
const L={toArray:v=>v==null?[]:Array.isArray(v)?v:String(v).split(/\s+/),naturalCompare:(a,b)=>a.localeCompare(b),url:(...x)=>x.join('/')};
const src=fs.readFileSync(require('path').join(__dirname, '../htdocs/luci-static/resources/view/mlo.js'),'utf8');const v=Function('view','form','uci','ui','poll','rpc','L','_','E',src)({extend:x=>x},form,uci,{createHandlerFn:(c,f)=>(...args)=>f.apply(c,args)},{add:(fn,interval)=>{assert.equal(interval,5);tick=fn},remove:fn=>{assert.equal(fn,tick);removed++;}},rpc,L,x=>x,E);
(async()=>{let data=await v.load();let nodes=await v.render(data);document.body.append(nodes);assert.equal(count,1);let overview=nodes.querySelector('[data-mlo-overview-section]');assert(overview);assert(nodes.textContent.includes('1'));let p1=tick(),p2=tick();await Promise.all([p1,p2]);assert.equal(count,2);assert.strictEqual(nodes.querySelector('[data-mlo-overview-section]'),overview);fail=true;await tick();assert(nodes.querySelector('[data-mlo-runtime-section]').textContent.includes('Unavailable'));nodes.remove();await new Promise(resolve=>setTimeout(resolve,0));assert.equal(removed,1);assert.equal(count,3);console.log('PASS shared inflight, failed status unknown and detached view immediately unregisters polling');})().catch(e=>{console.error(e);process.exitCode=1});
