const fs=require('fs'), vm=require('vm'), assert=require('assert'), path=require('path');
const root=path.join(__dirname,'..');
const s=fs.readFileSync(path.join(root,'root/etc/homeproxy/scripts/homeproxy.uc'),'utf8');
const a=s.indexOf('export function requirePort(');
assert(a>=0,'strict shared port validation required');
const ctx={match:(s,r)=>s.match(r),int:Number,die:s=>{throw Error(s)}};
vm.createContext(ctx); vm.runInContext(s.slice(a,s.indexOf('\n};',a)+3).replace('export ',''),ctx);
for(const p of ['',null,'auto','0','65536','12x','1.5','-1',' 53']) assert.throws(()=>ctx.requirePort(p),/port/i);
for(const p of ['1','53','65535']) assert.equal(ctx.requirePort(p),Number(p));
console.log('PASS strict port boundaries');
const client=fs.readFileSync(path.join(root,'root/etc/homeproxy/scripts/generate_client.uc'),'utf8');
const b=client.indexOf('const used_ports = {}'),end=client.indexOf('\nreserve_port(dns_port',b);
vm.runInContext(client.slice(b,end),ctx);
ctx.reserve_port('53','dns');
assert.throws(()=>ctx.reserve_port('53','mixed'),/conflict/);
ctx.reserve_port('5330','mixed');
console.log('PASS listener conflict guard');
