const fs=require('fs'),assert=require('assert/strict'),{JSDOM}=require('jsdom');
const j=new JSDOM('<body></body>',{runScripts:'outside-only'}),w=j.window;
w.eval(fs.readFileSync(process.env.LUCI_RESOURCE_DIR+'/luci.js','utf8').replace('window.LuCI = LuCI;','window.LuCI = LuCI; window.mods=classes;'));
w.eval("String.prototype.format = function(...a) { let i=0; return this.replace(/%[sh]/g,()=>String(a[i++])); }; String.format=(s,...a)=>s.format(...a);");
String.prototype.format=function(...args){return w.String.prototype.format.apply(this,args);};
const dom=w.mods.dom;w.E=(tag,attrs,children)=>dom.create(tag,w.Object.assign(new w.Object(),attrs||{}),Array.isArray(children)?w.Array.from(children):children);w._=s=>s;
w.L={env:{pollinterval:5},resolveDefault:(p,d)=>p.catch(()=>d),bind:(f,c,...a)=>f.bind(c,...a)};
let polls=[],text='alpha\nbeta\ngamma',err;
const rpc={declare:()=>()=>Promise.resolve({})},poll={add:f=>polls.push(f),remove:f=>{const i=polls.indexOf(f);if(i>=0)polls.splice(i,1);}},ui={createHandlerFn:(_c,f)=>f},uci={get:()=> 'warn'};
let s=fs.readFileSync(__dirname+'/../htdocs/luci-static/resources/view/homeproxy/status.js','utf8');s=s.slice(0,s.indexOf('return view.extend'))+'\nreturn {getRuntimeLog,css};';
const api=w.Function('dom','rpc','poll','fs','ui','uci',s)(dom,rpc,poll,{read_direct:()=>err?Promise.reject(err):Promise.resolve(text)},ui,uci);
const o={option:'_sing-box-c_logview',cbid:()=> 'fixture',map:{save:()=>Promise.resolve()}};
(async()=>{try{
 const root=w.E('div',{'class':'homeproxy-status'},[w.E('style',{},[api.css]),api.getRuntimeLog(o,'sing-box Client',0,'config')]);w.document.body.append(root);
 await polls[0]();const t=root.querySelector('textarea');assert(t&&t.readOnly);assert.equal(t.value,text);assert.equal(w.getComputedStyle(t).height,'256px');
 t.focus();t.setSelectionRange(1,5,'backward');t.scrollTop=12;t.scrollLeft=4;await polls[0]();assert.equal(t.selectionStart,1);assert.equal(t.selectionEnd,5);
 text+='\n<img src=x onerror=alert(1)>';await polls[0]();assert.equal(t.selectionStart,1);assert.equal(t.selectionEnd,5);assert.equal(t.selectionDirection,'backward');assert.equal(t.scrollTop,12);assert.equal(t.scrollLeft,4);assert.equal(root.querySelector('img'),null);
 err=new Error('NotFoundError');await polls[0]();assert.equal(t.value,'Log file does not exist.');
 const c=fs.readFileSync(__dirname+'/../htdocs/luci-static/resources/view/homeproxy/client.js','utf8');let a=c.indexOf('function renderTailscaleStatus('),b=c.indexOf('\nlet stubValidator',a);const render=w.Function(c.slice(a,b)+'\nreturn renderTailscaleStatus;')();
 assert.equal(render({state:'Running'}).textContent,'Connected');assert.equal(render({state:'NeedsLogin',auth_url:'javascript:alert(1)'}).tagName,'SPAN');assert.equal(render({state:'NeedsLogin',auth_url:'https://login.tailscale.com/a'}).tagName,'A');assert.equal(render({auth_url:'https://user:pass@example.com/'}).tagName,'SPAN');
 const n=fs.readFileSync(__dirname+'/../htdocs/luci-static/resources/view/homeproxy/node.js','utf8');a=n.indexOf('function parseECHConfig(');b=n.indexOf('\nreturn view.extend',a);if(b<0)b=n.indexOf('\nreturn ',a);
 const end=n.indexOf('\nreturn view.extend');const pre=n.slice(a,n.indexOf('\nfunction ',n.indexOf('function parseShareLink(',a)+10));
 const parse=w.Function('hp',pre+'\nreturn parseShareLink;')({decodeBase64Str:x=>w.atob(x)});
 const node=parse('vless://00000000-0000-4000-8000-000000000001@example.com:443?security=tls&ech=example.com%2Bhttps%3A%2F%2F1.1.1.1%2Fdns-query',{});assert.equal(node.type,'vless');assert.equal(node.tls_ech_query_server,'https://1.1.1.1/dns-query');assert.throws(()=>parse('vless://00000000-0000-4000-8000-000000000001@example.com:443?type=xhttp',{}),/Unsupported transport/);
 console.log('PASS real LuCI DOM log selection/scroll/literal text/scoped height; Tailscale login URL filtering; VLESS omitted TCP/ECH import and xhttp rejection');
}finally{w.close();}})().catch(e=>{console.error(e);process.exitCode=1});
